const TIME_WINDOWS = {
    cookingMorning: { start: 9, end: 13 },
    cookingNight: { start: 20, end: 23 },
    dishMorning: { start: 9, end: 12 },
    dishNight: { start: 19, end: 22 },
};

const CATEGORY_GROCERIES = 'groceries';
const CATEGORY_VEGETABLES = 'vegetables';

const INITIAL_EXPECTED_AMOUNTS = {
    [CATEGORY_GROCERIES]: 1000,
    [CATEGORY_VEGETABLES]: 500,
};

const NOTIFICATION_TYPES = {
    LOW_WATER: 'LOW_WATER',
    VEG_NEGATIVE: 'VEG_NEGATIVE',
    COOKING_DELAYED: 'COOKING_DELAYED',
    WATER_DUTY: 'WATER_DUTY',
    COOKING_PENDING: 'COOKING_PENDING',
    DISH: 'DISH',
    CLEANING: 'CLEANING',
    MARKET: 'MARKET',
    COOKING_WINDOW: 'COOKING_WINDOW',
    UPCOMING_DUTY: 'UPCOMING_DUTY',
    VEG_LOW: 'VEG_LOW',
    FINANCE_INFO: 'FINANCE_INFO',
    GROUP_SOCIAL: 'GROUP_SOCIAL',
    TRANSIENT: 'TRANSIENT',
};

const NOTIFICATION_PRIORITY = [
    NOTIFICATION_TYPES.LOW_WATER,
    NOTIFICATION_TYPES.VEG_NEGATIVE,
    NOTIFICATION_TYPES.COOKING_DELAYED,
    NOTIFICATION_TYPES.WATER_DUTY,
    NOTIFICATION_TYPES.COOKING_PENDING,
    NOTIFICATION_TYPES.DISH,
    NOTIFICATION_TYPES.CLEANING,
    NOTIFICATION_TYPES.MARKET,
    NOTIFICATION_TYPES.COOKING_WINDOW,
    NOTIFICATION_TYPES.UPCOMING_DUTY,
    NOTIFICATION_TYPES.VEG_LOW,
    NOTIFICATION_TYPES.FINANCE_INFO,
    NOTIFICATION_TYPES.GROUP_SOCIAL,
];

export {
    NOTIFICATION_TYPES,
    NOTIFICATION_PRIORITY,
    TIME_WINDOWS,
    CATEGORY_GROCERIES,

    CATEGORY_VEGETABLES,
    INITIAL_EXPECTED_AMOUNTS,
};
